### ISSUE TITLE
Exception: Null reference @if(_pane.lenght>1)

### ISSUE THREAD

**Issue by wcrisafu** [oqtane/oqtane.theme.cerulean#2] opened 2020-08-19 17:45 UTC
When I try to use the theme I get the following error. I did not make any changes to the base code or this theme but for some reason the "pane" comes up always "null":
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Oqtane.Client
  StackTrace:
   at Oqtane.Themes.Controls.ControlPanel.BuildRenderTree(RenderTreeBuilder __builder) in C:\Users\willi\Source\Repos\Oqtane\oqtane.framework\Oqtane.Client\Themes\Controls\ControlPanel.razor:line 165

**Comment by sbwalker** [comment] 2020-08-19 18:09
there was a PR which was merged for the Control Panel which changed the original logic and appears to have an issue related to asynchronous loading as it is referencing a variable without checking if it is initialized. Are you able to provide the steps to reproduce the problem? Did you install the Cerulean theme through the Theme Management screen in the Admin Dashboard?

**Comment by wcrisafu** [comment] 2020-08-19 18:59
For now I ma just playing with Visual studio to learn Oqtane. At recompile the files are copied by the batch file to the bin folder and when I restart Oqtane from VS the theme is loaded automatically.

**Comment by sbwalker** [comment] 2020-08-19 19:52
Ok, so you are working directly from the source code - that;s helpful to know. Once the theme is automatically loaded, is there any specific action you took in order to trigger the error? ie. does it happen immediately when you login, only when you select it in the dropdown within the control panel, after you have assigned it to a site, after you have assigned it to a page... there are many scenarios and it would help to be able to reproduce it.

**Comment by wcrisafu** [comment] 2020-08-19 20:00
I created  a new page and selected the theme. All the other pages work (with either of the two themes: Oqtane or Blazor). I actually created two pages. In one I used Blazor theme and in one the Cerulan. As soon as I click the new page with the Cerulan theme, i get the error. If I go to the database, open the "page" table and remove the "ThemeType" entry, the page will reload as usual. 

I started the debugging and the issue seems to be when it tries to LoadSettingAsync, the "_pane" is null.

**Comment by sbwalker** [comment] 2020-08-19 21:17
I am unable to reproduce this problem locally - but this is not unusual for issues related to asynchronous processing, as it is dependent on the hardware performance in regards to whether the issue is triggered or not. I will try a few techniques to imitate the problem.

**Comment by sbwalker** [comment] 2020-08-19 21:42
I cannot reproduce the problem so I am trying to understand what is different about your configuration. When you created the new page what did you specify for the View and Edit permissions? And are you logged in or logged out when you navigate to the new page?

**Comment by wcrisafu** [comment] 2020-08-19 23:41
Ok, I know it may sound strange but the error is gone.... for now. This is what I did:

1. Super basic setting, no changes, default 3 roles and logged as host
2. Created 3 pages.  Each has a different permission (just in case). 
3. Page 1 has Cerulean theme and the Layout set to single pane (i did not do this before).
4. Page 2 has Cerulean theme and inherited from site layout (I get the error)
5. Page 3 has Blazor and inherited from site layout (no errors)

If I start and go to page 2, I get the error (and I need to restart)
If I go to page 3, then page 2. I get the error (and I need to restart)
If I go to page 1 (the one with Cerulean and  the layout changed) and then go to page 2. I am totally fine, no errors no matter how many times i switch. Of course as soon as I restart.... i get the error again unless I stop by page 1

**Comment by sbwalker** [comment] 2020-08-24 02:16
I located the problem. The Add Page feature has a bug where it is not validating the inputs correctly. If a theme uses layouts then it should force the use to select a layout from the list. Since the layout is not being set the page throws an error when the control panel is displayed.

**Comment by sbwalker** [comment] 2020-08-26 19:01
This should be fixed by https://github.com/oqtane/oqtane.framework/pull/705. Thank you for you help.

**Closed by sbwalker** 2020-08-26 19:01 UTC
